# version: '3.8'

# services:
#   smart-paddy:
#     container_name: smart-paddy-app
#     build: .
#     restart: always  # ถ้าระบบล่ม ให้ลุกขึ้นมาเองอัตโนมัติ
#     ports:
#       - "3000:3000" # แมพ Port 3000 เครื่องจริง เข้า 3000 ใน Container
#     environment:
#       - NODE_ENV=production


services:
  smart-paddy:
    container_name: smart-paddy-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
