services:
  frontend:
    image: suphanat10/paddy-frontend:latest
    container_name: backend-paddy-frontend
    ports:
      - "3000:3000"
    depends_on:
      - node-server
    networks:
      - paddy-net
    restart: unless-stopped
